// City-page configs for /locations/<slug>/. Each entry must have unique
// intro/why/landmarks copy — Google penalizes boilerplate-swapped local pages.

module.exports = [
  {
    slug: 'vancouver',
    city: 'Vancouver',
    region: 'BC',
    lat: 49.2827, lon: -123.1207,
    neighborhoods: ['Mount Pleasant', 'Kitsilano', 'Yaletown', 'Gastown', 'Mount Pleasant', 'Marpole', 'Dunbar', 'Fraserview', 'East Van', 'Downtown', 'False Creek'],
    landmarks: ['Stanley Park', 'BC Place', 'Granville Island', 'Science World', 'the SeaBus', 'Robson Street', 'Commercial Drive'],
    nearby: ['burnaby', 'surrey', 'squamish'],
    intro: `Vancouver runs on local search. Every restaurant, clinic, salon, contractor, and showroom in this city lives or dies by whether they show up when someone in Mount Pleasant searches for "best <whatever> near me." We come on-site across every Vancouver neighborhood to install the AI systems that get that phone ringing — and keep it ringing while you're working.`,
    why: [
      `Vancouver businesses fight harder for attention than almost anywhere in Canada. The competition is denser, the customer is pickier, the rent demands faster cashflow. Generic AI tools that work in a small town fail here because they were never built for a market this saturated.`,
      `Our Small Business Starter is the package most Vancouver shops, studios, and service businesses come in on. One flat $599/month — no setup fee, 6-month commit — covers a premium website, your Google Business Profile fully optimized, a real CRM that tracks every lead, basic AI on every channel, and the local SEO that puts you in front of the people already searching for you.`,
      `Everything is installed on-site at your Vancouver location. We sit with you, train your staff, and stay on call. After 30+ Vancouver-area installs, we know the city's quirks — what works in Kitsilano doesn't always work in Mount Pleasant, and we'll tell you which is which.`,
    ],
    faq: [
      { q: 'Do you actually come into Vancouver to install?', a: 'Yes. Every Vancouver client gets an on-site visit at your location for the install and first training session. We bring laptops, walk through every tool with you, and don\'t leave until your team can run it without us.' },
      { q: 'How long until I rank on Google in Vancouver?', a: 'Map Pack appearances typically inside 30 days once your Google Business Profile is fully optimized and citation work is done. Page-one organic for competitive Vancouver terms is usually a 60-120 day curve, longer for terms with strong incumbents. We send monthly rank reports so you see exactly where you stand.' },
      { q: 'Which Vancouver neighborhoods do you serve?', a: 'All of them. Downtown, the West Side, East Van, North Van, the Tri-Cities — anywhere a Vancouverite would call Vancouver. If you\'re in Burnaby, Richmond, or Surrey, we still come to you; we just call those by their own names.' },
    ],
  },
  {
    slug: 'surrey',
    city: 'Surrey',
    region: 'BC',
    lat: 49.1913, lon: -122.8490,
    neighborhoods: ['Cloverdale', 'Newton', 'Guildford', 'Whalley', 'South Surrey', 'Fleetwood', 'North Surrey'],
    landmarks: ['the Surrey Civic Plaza', 'Holland Park', 'Bear Creek Park', 'Surrey Memorial Hospital', 'the SkyTrain Expo Line'],
    nearby: ['langley', 'burnaby', 'vancouver'],
    intro: `Surrey is the city that's growing faster than anyone planned for. New developments, new businesses, new neighborhoods sprouting in Clayton and South Surrey and Grandview — and almost none of them have the AI infrastructure to keep up with the demand they're already seeing. That's where we come in.`,
    why: [
      `Surrey businesses have a particular problem: the customer base is huge, the area is spread out, and most local services can't physically scale fast enough to capture the demand. AI is the equalizer. A two-person shop in Newton can answer calls 24/7 and book appointments while they're elbow-deep in a job, just like a 20-person operation downtown.`,
      `Our Small Business Starter ($599/mo, no setup, 6-month commit) is the entry point for most Surrey businesses. It covers a premium website built for your trade, your Google Business Profile fully claimed and optimized, CRM, basic AI receptionist, and the local SEO push that finally puts you in the Map Pack for Surrey searches.`,
      `We install on-site at your Surrey location, train your team there, and stay on call. Surrey-specific advice: GBP listings here punch above their weight because Surrey customers search by neighborhood ("dentist in Cloverdale," "physio Newton") more than by city. We optimize for that pattern.`,
    ],
    faq: [
      { q: 'I\'m in Cloverdale / Newton / South Surrey. Do you actually come out?', a: 'Yes. Every quadrant of Surrey, every install on-site. We drive there, set up at your location, and train your team in person.' },
      { q: 'Why does my Surrey competitor show up before me on Google?', a: 'Usually one of two reasons: their Google Business Profile is more complete (categories, photos, services, posts, reviews), or they\'re built into more local directories. Both are fixable in 30-60 days with the Starter.' },
      { q: 'Do you work with South Asian-language businesses in Surrey?', a: 'Yes. Many of our Surrey clients run multilingual operations. Our AI receptionist handles English/Punjabi/Hindi calls, and we can build your site multilingual when it matters.' },
    ],
  },
  {
    slug: 'burnaby',
    city: 'Burnaby',
    region: 'BC',
    lat: 49.2488, lon: -122.9805,
    neighborhoods: ['Metrotown', 'Brentwood', 'Lougheed', 'Edmonds', 'Burnaby Heights', 'Capitol Hill'],
    landmarks: ['Metropolis at Metrotown', 'Burnaby Mountain', 'Deer Lake', 'SFU', 'the Brentwood Town Centre'],
    nearby: ['vancouver', 'surrey', 'langley'],
    intro: `Burnaby has a tricky reputation in local search. Customers in Metrotown often search "Vancouver," customers in Burnaby Heights often search "Burnaby," and the businesses in between fight to show up for both. We solve that.`,
    why: [
      `If you serve customers in both Burnaby and Vancouver — which most Burnaby businesses do — you need a Google Business Profile and a website that targets both markets without confusing Google about where you actually are. That's specific work, not a checkbox.`,
      `Small Business Starter ($599/mo) covers the foundation: GBP claim and full optimization (service area set correctly), website, CRM, basic AI receptionist, and the cross-city SEO that puts you on the map for searches in both directions.`,
      `On-site install across every part of Burnaby — Metrotown corridor, Brentwood, Lougheed, Edmonds, the Heights. We're physically here regularly because many of our Vancouver and Surrey clients are right next door.`,
    ],
    faq: [
      { q: 'My business is on the Vancouver/Burnaby border. Which city should my listing say?', a: 'Your registered business address. Don\'t fake it — Google catches that and downranks. We set the service area so you legitimately rank in both cities.' },
      { q: 'How do you handle Burnaby Mountain and SFU-adjacent businesses?', a: 'Those are micro-markets with their own search patterns (students, faculty, campus services). We build city pages and content that target the SFU corridor specifically when it matters.' },
    ],
  },
  {
    slug: 'langley',
    city: 'Langley',
    region: 'BC',
    lat: 49.1041, lon: -122.6604,
    neighborhoods: ['Willoughby', 'Walnut Grove', 'Murrayville', 'Aldergrove', 'Brookswood', 'Fort Langley', 'Township'],
    landmarks: ['Fort Langley', 'Willowbrook Mall', 'Langley Events Centre', 'Township of Langley', 'the Aldergrove border'],
    nearby: ['surrey', 'abbotsford', 'burnaby'],
    intro: `Langley is two cities pretending to be one — the City of Langley and the Township around it. They search differently, they shop differently, and most local businesses miss out on half the market because their SEO only targets one. That's the gap we close here.`,
    why: [
      `Langley businesses serve a customer base that drives. People in Willoughby drive to Walnut Grove. People in Murrayville drive to Aldergrove. If your Google presence doesn't make it obvious you serve that whole radius, you're invisible to half your real audience.`,
      `Starter ($599/mo) covers the foundation: GBP claim and full optimization with a service area that covers the Township properly, a website that loads fast on the rural-edge connections common east of 264th, CRM, basic AI receptionist, and Township-aware local SEO.`,
      `On-site install across both Langley City and the Township. We've been to Fort Langley, the Murrayville corridor, the Willoughby townhouse developments, and the rural east side. We know where the cell coverage drops and where it doesn't — matters more than people think.`,
    ],
    faq: [
      { q: 'I serve the Township, not the city. Does that change anything?', a: 'Yes, importantly. Township businesses need a "Township of Langley" service area on GBP, not just "Langley." Customers search differently for each. We set this correctly.' },
      { q: 'Can you handle agricultural/equestrian businesses in south Langley?', a: 'Yes — that\'s a specific local market we\'ve worked with. Long-form content about specific services (boarding, training, vet, feed, equipment) ranks well because there\'s less local competition.' },
    ],
  },
  {
    slug: 'abbotsford',
    city: 'Abbotsford',
    region: 'BC',
    lat: 49.0504, lon: -122.3045,
    neighborhoods: ['Clearbrook', 'McCallum', 'Sumas Mountain', 'Mill Lake', 'Sevenoaks', 'Matsqui'],
    landmarks: ['Mill Lake', 'Sevenoaks Shopping Centre', 'the Abbotsford airport', 'University of the Fraser Valley', 'Sumas Mountain'],
    nearby: ['chilliwack', 'langley'],
    intro: `Abbotsford has the largest farming community in BC sitting right next to a university, an airport, and one of the fastest-growing residential markets in the Lower Mainland. The mix is unusual. Most generic SEO and AI tools don't understand it. We do.`,
    why: [
      `An Abbotsford business is often serving farms and families and students all at once. That breadth is your advantage if your AI and content reflect it — generic city pages don't, ours do.`,
      `Starter ($599/mo) covers the foundation: GBP claim and full optimization with a service area covering Matsqui and Sumas, a website built for Fraser Valley load times, CRM, basic AI receptionist, and Fraser-Valley-specific local SEO that doesn't try to compete with Vancouver SERPs.`,
      `We come to Abbotsford. Every install, every monthly check-in. The drive is worth it because Abbotsford clients tend to refer harder than anywhere else — the community is tight, word travels fast.`,
    ],
    faq: [
      { q: 'Do you cover Mission and the rural Fraser Valley too?', a: 'Yes. Mission, Hatzic, Deroche — we drive out for installs. Mission has its own GBP behaviour worth optimizing for separately.' },
      { q: 'My Abbotsford business is dual-language. Does that work with your AI?', a: 'Yes. Punjabi, Hindi, Korean, Dutch (yes, there\'s a community), German Mennonite — our AI receptionist supports the major Fraser Valley language pairs.' },
    ],
  },
  {
    slug: 'chilliwack',
    city: 'Chilliwack',
    region: 'BC',
    lat: 49.1579, lon: -121.9515,
    neighborhoods: ['Sardis', 'Garrison Crossing', 'Vedder', 'Promontory', 'Yarrow', 'Rosedale', 'Greendale'],
    landmarks: ['Cultus Lake', 'Mount Cheam', 'the Vedder River', 'Cottonwood Mall', 'the Chilliwack Heritage Park'],
    nearby: ['abbotsford'],
    intro: `Chilliwack is the eastern edge of how far most Vancouver-based companies will drive. Most won't. We will. That alone makes us different — and it's why Chilliwack businesses tend to lean hard on a partner who actually shows up.`,
    why: [
      `Chilliwack businesses are usually undercompeted in local search compared to the Lower Mainland — which means a properly optimized GBP and a real local content strategy can put you in the Map Pack faster here than almost anywhere else.`,
      `Starter ($599/mo) covers it: GBP claim with proper Chilliwack service area (Sardis, Promontory, Yarrow — search patterns differ), a website that loads fast on rural connections, CRM, basic AI receptionist, and the local SEO that captures both Chilliwack and Cultus Lake summer traffic.`,
      `We come to Chilliwack for on-site installs. Yes, the drive. That's the point. The local Chilliwack businesses who hire us tell us "you actually came" is the reason they signed.`,
    ],
    faq: [
      { q: 'Is the on-site install really worth the drive from Vancouver?', a: 'For us, yes. For you, it matters because the install runs better in person — your team learns it, your specific tools get integrated, and we catch the local quirks. Remote installs work too but we prefer to come once.' },
      { q: 'Cultus Lake / summer market — do you handle seasonal businesses?', a: 'Yes. We can put your AI and content into a seasonal mode (high pace May-September, dialed back October-April) so you\'re not paying for capacity you don\'t need in the slow months.' },
    ],
  },
  {
    slug: 'squamish',
    city: 'Squamish',
    region: 'BC',
    lat: 49.7016, lon: -123.1558,
    neighborhoods: ['Downtown Squamish', 'Garibaldi Highlands', 'Brackendale', 'Valleycliffe', 'Britannia Beach'],
    landmarks: ['the Stawamus Chief', 'Shannon Falls', 'the Squamish River', 'the Sea-to-Sky Gondola', 'Garibaldi Provincial Park'],
    nearby: ['whistler', 'vancouver'],
    intro: `Squamish is the fastest-growing town on the Sea-to-Sky and one of the trickiest local-search markets in BC. Your customers are split between Squamish locals, Vancouver weekenders, and a constantly rotating tourist population. Generic SEO tools don't know how to handle that. We do.`,
    why: [
      `A Squamish business needs to rank for "Squamish" searches AND show up in Vancouver-area searches when someone is planning a weekend up. Most local SEO treats those as the same problem; they aren't.`,
      `Starter ($599/mo) covers the foundation: GBP claim, website built to handle high-bandwidth visuals (outdoor businesses live on photos), CRM, basic AI receptionist, and a SEO setup that targets both the local market and the inbound Vancouver visitor market.`,
      `On-site install means we drive up the Sea-to-Sky. We're up there often — Squamish and Whistler clients run in the same week. The on-site visit matters even more here because cell service is patchy in places and your tech has to work without constant connectivity.`,
    ],
    faq: [
      { q: 'How do you handle the tourist vs. local split?', a: 'Two pages or two services on your site — one targeted at locals (regulars, repeat customers, loyalty), one at weekend visitors (booking, info, what to expect). Both feed into the same CRM but speak different languages.' },
      { q: 'Do you cover Britannia Beach and the Sea-to-Sky corridor?', a: 'Yes. Britannia, Furry Creek, Lions Bay — anywhere on the corridor. We add corridor coverage to the GBP service area properly.' },
    ],
  },
  {
    slug: 'whistler',
    city: 'Whistler',
    region: 'BC',
    lat: 50.1163, lon: -122.9574,
    neighborhoods: ['Whistler Village', 'Creekside', 'Function Junction', 'Alpine Meadows', 'Whistler Cay'],
    landmarks: ['Whistler Blackcomb', 'the Peak 2 Peak Gondola', 'the Village Stroll', 'Lost Lake', 'Alta Lake'],
    nearby: ['squamish', 'vancouver'],
    intro: `Whistler is the most international local market in BC. Your customers might be from down the road in Function Junction or from Sydney, Munich, or Toronto — and they all search differently, in different languages, on different devices. Your AI has to handle every one of them gracefully.`,
    why: [
      `A Whistler business needs to appear correctly in Google for "Whistler" but also for season-specific searches ("Whistler skiing," "Whistler summer," "Whistler dining") that have wildly different traffic patterns. Generic SEO levels them all; we don't.`,
      `Starter ($599/mo) covers GBP optimization for Whistler's specific seasonality, a website built fast for the high-bandwidth visual content Whistler customers expect, multi-language CRM (English/French/German/Mandarin commonly), AI receptionist that handles tourist questions politely without burning your team's time, and a SEO setup that knows when ski-season terms outrank summer terms.`,
      `On-site install in Whistler. Yes, we make the drive. We pair Whistler visits with Squamish or weekend installs and treat the corridor as a single service region.`,
    ],
    faq: [
      { q: 'My business is seasonal. Will my AI sit idle in shoulder season?', a: 'No — we configure your AI for "shoulder mode" automatically. Less capacity, lower cost, still online to capture early-season inquiries. Bumps back up when bookings spike.' },
      { q: 'Can your AI handle non-English calls from international tourists?', a: 'Yes. English, French, German, Mandarin, Japanese, Spanish — the major Whistler languages. We configure based on your actual customer mix.' },
    ],
  },
  {
    slug: 'coquitlam',
    city: 'Coquitlam',
    region: 'BC',
    lat: 49.2838, lon: -122.7932,
    neighborhoods: ['Coquitlam Centre', 'Burquitlam', 'Maillardville', 'Westwood Plateau', 'Austin Heights', 'Port Coquitlam', 'Port Moody', 'Burke Mountain'],
    landmarks: ['Coquitlam Centre', 'Lafarge Lake', 'the Evergreen Line', 'Mundy Park', 'Rocky Point Park', 'Town Centre Park'],
    nearby: ['burnaby', 'new-westminster', 'maple-ridge'],
    intro: `Coquitlam is three cities in one search area. Coquitlam, Port Coquitlam and Port Moody share customers, share the Evergreen Line, and share the same problem: every local business is competing for the same "near me" searches across the whole Tri-Cities and most of them are not set up to win. We come out to Coquitlam Centre, Burquitlam, Burke Mountain and the Ports to fix that on-site.`,
    why: [
      `Tri-Cities customers search by the place they are standing in, not the city on the business licence. Someone at Lafarge Lake types "physio Coquitlam." Someone in Burquitlam types "dentist near me" and Google decides whether that means you. Your Google Business Profile, your service area and your website have to agree on where you are and who you serve, or you lose both searches.`,
      `The Small Business Starter is the package most Coquitlam businesses come in on. One flat $599 a month, no setup fee, six month commit. It covers a premium website, your Google Business Profile properly built out, a real CRM, an AI receptionist that answers when you cannot, and the local SEO push that gets you into the Map Pack for Tri-Cities searches.`,
      `Everything is installed on-site. We come to your location in Coquitlam, Port Coquitlam or Port Moody, sit with your staff and do not leave until they can run it. Burnaby and New Westminster clients are next door, so we are in the area every week.`,
    ],
    faq: [
      { q: 'Do you cover Port Coquitlam and Port Moody too?', a: 'Yes. We treat the Tri-Cities as one service area. Your Google Business Profile gets all three cities set correctly so you show up in each of them without faking an address.' },
      { q: 'How is Coquitlam different from Burnaby for local SEO?', a: 'Less competition per search, but the searches are split across three city names. We set up your profile and pages so Google connects you to all three instead of just the one on your licence.' },
      { q: 'What does the first 30 days look like?', a: 'On-site install, Google Business Profile rebuilt, website live, CRM and AI receptionist answering. Map Pack movement usually shows inside the first month for Tri-Cities terms.' },
    ],
  },
  {
    slug: 'richmond',
    city: 'Richmond',
    region: 'BC',
    lat: 49.1666, lon: -123.1336,
    neighborhoods: ['Steveston', 'Brighouse', 'Ironwood', 'Hamilton', 'Terra Nova', 'Seafair', 'Bridgeport', 'Sea Island'],
    landmarks: ['Steveston Village', 'Richmond Centre', 'the Canada Line', 'YVR', 'Aberdeen Centre', 'the Richmond Olympic Oval', 'Garry Point Park'],
    nearby: ['vancouver', 'delta', 'burnaby'],
    intro: `Richmond is one of the most bilingual local markets in Canada, and Google knows it. A clinic in Brighouse, a shop in Steveston, a contractor working out of Ironwood: they are all being searched for in English and Chinese, on phones, from the Canada Line. Most Richmond businesses have a website that handles one of those and a Google profile that handles neither. We install the whole system on-site.`,
    why: [
      `Richmond searches are dense and fast. The customer is standing in Aberdeen Centre or Richmond Centre and wants an answer in the next two minutes. If your phone goes to voicemail or your profile has no hours and three photos, the next business on the list gets the call. An AI receptionist that answers every call and books straight into your calendar is the single biggest fix for Richmond service businesses.`,
      `The Small Business Starter covers it. One flat $599 a month, no setup fee, six month commit. Premium website, Google Business Profile fully built, CRM, AI receptionist and the local SEO that puts you in the Map Pack for Richmond and Steveston searches. Multilingual handling is available when your customers need it.`,
      `We install on-site anywhere in Richmond, including Sea Island and the industrial areas around Bridgeport. Vancouver and Delta clients are minutes away, so we are on the Canada Line corridor constantly.`,
    ],
    faq: [
      { q: 'Can the AI receptionist handle Cantonese or Mandarin callers?', a: 'Yes. We configure the receptionist for the languages your customers actually use, and we can build your website bilingual when it matters for your market.' },
      { q: 'I am in Steveston. Do I rank for Richmond or for Steveston?', a: 'Both, if it is set up right. Steveston is its own search term with its own Map Pack. We build your profile and a page so you show for the village and for the city.' },
      { q: 'Do you work with businesses near YVR and Sea Island?', a: 'Yes. Airport-adjacent businesses get a lot of "near me" traffic from travellers. We optimize for that pattern specifically.' },
    ],
  },
  {
    slug: 'delta',
    city: 'Delta',
    region: 'BC',
    lat: 49.0847, lon: -123.0587,
    neighborhoods: ['Ladner', 'Tsawwassen', 'North Delta', 'Sunshine Hills', 'Scottsdale', 'Annieville', 'Boundary Bay'],
    landmarks: ['Ladner Village', 'the Tsawwassen Ferry Terminal', 'Tsawwassen Mills', 'Burns Bog', 'Boundary Bay', 'the Alex Fraser Bridge'],
    nearby: ['richmond', 'surrey', 'vancouver'],
    intro: `Delta is where Easyworks is based, and it is the clearest example we have of a place Google gets wrong. Ladner, Tsawwassen and North Delta are three separate communities that happen to share a city name, separated by farmland and a highway. A North Delta customer will never drive to Ladner for a haircut, but Google will happily show them a Ladner salon and skip yours. We fix that from home turf.`,
    why: [
      `Delta businesses need their Google Business Profile to name the community, not just the city. "Dentist Tsawwassen" and "dentist North Delta" are different searches with different winners. Most Delta profiles say "Delta" and lose both. We set the service area and the page copy so you own your own community first.`,
      `The Small Business Starter is built for exactly this size of business. One flat $599 a month, no setup fee, six month commit. Premium website, Google Business Profile rebuilt, CRM, AI receptionist, and the local SEO that puts you in the Map Pack for Ladner, Tsawwassen or North Delta searches.`,
      `We are local. On-site install anywhere in Delta is a short drive for us, and we are around Ladner Village and the Scottsdale corridor all the time. When something needs a hand, we come by.`,
    ],
    faq: [
      { q: 'Is Easyworks actually in Delta?', a: 'Yes. Delta is home base. Every other BC city we serve, we drive to from here.' },
      { q: 'I am in Tsawwassen. Will I show up for ferry traffic searches?', a: 'That is a real opportunity. Thousands of people a day search "near me" from the terminal line-up. We optimize your profile and hours so you catch that traffic.' },
      { q: 'Do you serve the farms and agricultural businesses out by Boundary Bay?', a: 'Yes. Farm stands, nurseries, equipment and services all rank well locally because there is little competition. Long-form content about what you actually offer does the work.' },
    ],
  },
  {
    slug: 'new-westminster',
    city: 'New Westminster',
    region: 'BC',
    lat: 49.2057, lon: -122.9110,
    neighborhoods: ['Downtown New West', 'Sapperton', 'Queensborough', 'Uptown', 'the Quay', 'Brow of the Hill', 'West End'],
    landmarks: ['the River Market', 'Westminster Quay', 'Royal Columbian Hospital', 'Columbia Street', 'Queens Park', 'the Pattullo Bridge'],
    nearby: ['burnaby', 'coquitlam', 'surrey'],
    intro: `New Westminster is small, dense and surrounded. Burnaby on one side, Surrey across the river, Coquitlam up the hill. That means a New West business shows up in three cities' worth of searches if the setup is right, and gets buried under three cities' worth of competitors if it is not. Most Columbia Street and Sapperton businesses are in the second group. We change that on-site.`,
    why: [
      `Downtown New West, Sapperton and Queensborough are three distinct search areas on a very small map. A Royal Columbian nurse searching "lunch near me" and a Quay resident searching "physio New Westminster" are both your customer, and Google decides which businesses it shows each of them based on how complete and consistent your profile is. Completeness wins here more than anywhere in Metro Vancouver.`,
      `The Small Business Starter covers it. One flat $599 a month, no setup fee, six month commit. Premium website, Google Business Profile fully built, CRM, AI receptionist for the calls you miss, and the local SEO that puts you in the Map Pack for New West and the neighbouring cities.`,
      `We install on-site. Columbia Street, Sapperton, Uptown, Queensborough, all of it. Burnaby and Coquitlam clients are minutes away, so we are on this side of the river weekly.`,
    ],
    faq: [
      { q: 'Should my Google profile say New Westminster or Burnaby?', a: 'Your real address, always. Then we set the service area to cover the cities you actually serve so you rank across the border without faking anything.' },
      { q: 'How do I catch the Royal Columbian Hospital traffic?', a: 'Staff and visitors search "near me" from the hospital all day. Accurate hours, a complete profile and Sapperton-specific page copy put you in front of them.' },
      { q: 'Is Queensborough treated as New West or Richmond?', a: 'Google leans New West, customers lean both. We optimize for both names so you do not lose the Richmond-side searches.' },
    ],
  },
  {
    slug: 'north-vancouver',
    city: 'North Vancouver',
    region: 'BC',
    lat: 49.3200, lon: -123.0724,
    neighborhoods: ['Lonsdale', 'Lynn Valley', 'Deep Cove', 'Edgemont', 'Lower Lonsdale', 'Capilano', 'Seymour', 'West Vancouver'],
    landmarks: ['the Lonsdale Quay', 'Lynn Canyon', 'Grouse Mountain', 'the Capilano Suspension Bridge', 'Deep Cove', 'Park Royal', 'the Lions Gate Bridge'],
    nearby: ['vancouver', 'squamish', 'burnaby'],
    intro: `The North Shore has a bridge problem. Customers on this side do not want to cross Lions Gate or the Second Narrows for anything they can get in Lonsdale, Lynn Valley or Edgemont, and they search accordingly. Google, though, keeps showing them Vancouver businesses because the North Shore listings are thin. A well built North Van profile beats a downtown competitor here almost every time. We build it on-site.`,
    why: [
      `North Vancouver customers are loyal to the North Shore and search by neighbourhood. "Dentist Lynn Valley," "physio Lower Lonsdale," "spa Edgemont." If your Google Business Profile and website name the neighbourhood, you win those searches with less competition than anywhere south of the bridges. West Vancouver works the same way.`,
      `The Small Business Starter covers the foundation. One flat $599 a month, no setup fee, six month commit. Premium website, Google Business Profile rebuilt with the right neighbourhood and service area, CRM, AI receptionist, and the local SEO that puts you in the North Shore Map Pack.`,
      `We install on-site across North Van, West Van and out to Deep Cove. We are also on the Sea to Sky for Squamish and Whistler clients, so the North Shore is on the way.`,
    ],
    faq: [
      { q: 'Do you cover West Vancouver as well?', a: 'Yes. We treat the North Shore as one service area and set your profile to cover the District, the City and West Van correctly.' },
      { q: 'Does the tourist traffic at Grouse and Capilano help local businesses?', a: 'A lot, if you are set up for it. Visitors search "near me" constantly. Complete hours, photos and a fast mobile site convert that traffic.' },
      { q: 'Why do Vancouver businesses outrank me on the North Shore?', a: 'Usually because their profiles are more complete and their sites load faster. Both are fixable in 30 to 60 days, and North Shore proximity works in your favour once they are.' },
    ],
  },
  {
    slug: 'maple-ridge',
    city: 'Maple Ridge',
    region: 'BC',
    lat: 49.2193, lon: -122.5984,
    neighborhoods: ['Haney', 'Albion', 'Silver Valley', 'Hammond', 'Whonnock', 'Pitt Meadows', 'Websters Corners', 'Thornhill'],
    landmarks: ['Golden Ears Provincial Park', 'the Haney Farmers Market', 'Alouette Lake', 'the Golden Ears Bridge', 'Kanaka Creek', 'the West Coast Express'],
    nearby: ['coquitlam', 'langley', 'abbotsford'],
    intro: `Maple Ridge and Pitt Meadows grew faster than their local business infrastructure. Albion and Silver Valley filled up with families who search for everything on their phones, and most of the businesses serving them still run on a Facebook page and a voicemail. That is the widest gap between demand and setup anywhere in the Fraser Valley, and it is the easiest to close.`,
    why: [
      `There is less competition per search here than anywhere west of the Golden Ears Bridge. A complete Google Business Profile, a fast website and an AI receptionist that actually answers put a Maple Ridge business at the top of the Map Pack faster than the same work would in Burnaby or Surrey. The customers are already searching; almost nobody is set up to be found.`,
      `The Small Business Starter is the entry point. One flat $599 a month, no setup fee, six month commit. Premium website, Google Business Profile rebuilt, CRM, AI receptionist, and the local SEO that covers Maple Ridge and Pitt Meadows as one market.`,
      `We install on-site in Haney, Albion, Silver Valley, Pitt Meadows and out to Whonnock. Langley and Coquitlam clients are close, so the Ridge is a regular stop.`,
    ],
    faq: [
      { q: 'Do you cover Pitt Meadows too?', a: 'Yes. Maple Ridge and Pitt Meadows share customers and searches. Your profile gets both set correctly.' },
      { q: 'How fast can a Maple Ridge business get into the Map Pack?', a: 'Often inside 30 days. Competition is lighter here, so a complete profile and consistent citations move quickly.' },
      { q: 'Do you work with trades and contractors out here?', a: 'A lot of our Fraser Valley clients are trades. The AI receptionist answering while you are on a job site is usually the first thing that pays for itself.' },
    ],
  },
];
