// Industry landers at /industries/<slug>/. Three priority verticals
// per project memory: dentist, physio, spa.

module.exports = [
  {
    slug: 'ai-for-dentists-bc',
    industry: 'Dental Clinics',
    region: 'BC',
    keywords: ['AI for dentists BC', 'dental office AI receptionist', 'dental practice automation Canada'],
    title: 'AI for Dental Clinics in BC',
    tagline: 'Book more cleanings. Reduce no-shows. Never miss an after-hours call.',
    intro: `Dental clinics in British Columbia lose more revenue to no-shows and missed phone calls than to any other category of operations problem. Patients call after hours. Patients call during a procedure when the front desk is helping someone else. Patients book online but no one follows up to confirm. Every one of those calls is a $300+ appointment slot. We close those gaps.`,
    services: [
      { name: 'AI Receptionist (24/7 call handling)', desc: 'Patients call after hours, the AI handles routine questions, books appointments directly into your operatory schedule, and texts a polite "we got your message" for anything that needs a human. Caps about 40% of after-hours calls without involving your staff.' },
      { name: 'No-show reduction', desc: 'Automated SMS confirmation sequence at 7 days, 24 hours, and 2 hours before the appointment. Patients can confirm or reschedule with one tap. Real BC dental clients see no-shows drop by 30-50%.' },
      { name: 'Recall automation', desc: 'Every cleaning recall hits the patient on time, every time, in their preferred channel. Patients who haven\'t booked in 9 months get a re-engagement sequence that brings 8-15% back in the door.' },
      { name: 'New-patient acquisition', desc: 'Local SEO plus a Google Business Profile fully optimized for dental categories puts you in the Map Pack for "dentist near me" in your specific BC city. Most BC clinics have terrible GBPs that we can fix in week one.' },
      { name: 'Insurance + treatment plan follow-up', desc: 'When a patient leaves with a recommended crown or implant plan, the system follows up at 7, 14, and 30 days with personalized reminders. Quietly significant for case-acceptance rates.' },
    ],
    why: [
      `We work with BC clinics specifically — PIPEDA compliance, Canadian data residency for patient information, and integration with the practice management software you already use (Tracker, ClearDent, Open Dental, Dentrix). We don't ask you to switch systems.`,
      `Most "AI for dentists" sold in BC is built for US clinics and quietly fails on Canadian compliance. We don't.`,
      `Every engagement starts with an audit of your phones, recall, reviews and Google presence. We build only what it finds, then run it for you every month.`,
    ],
    faq: [
      { q: 'Will the AI receptionist mishandle a medical emergency call?', a: 'No — the AI is trained to recognize emergency language and immediately escalate to your on-call protocol (text the dentist, route to your answering service, whatever you choose). It never tries to diagnose or delay.' },
      { q: 'Does it work with our practice management software?', a: 'Yes. Tracker, ClearDent, Open Dental, Dentrix, and a few others integrate directly. For everything else we set up a structured handoff so appointments still land where they need to.' },
      { q: 'Is patient data stored in the US?', a: 'No. All patient-facing data sits on Canadian-hosted infrastructure for PIPEDA compliance. We make the data residency map available on request.' },
    ],
  },
  {
    slug: 'ai-for-physio-bc',
    industry: 'Physiotherapy Clinics',
    region: 'BC',
    keywords: ['AI for physio BC', 'physiotherapy AI receptionist', 'physio clinic automation Canada'],
    title: 'AI for Physiotherapy Clinics in BC',
    tagline: 'Capture every ICBC and WSBC referral. Cut admin in half. Free your front desk.',
    intro: `BC physiotherapy clinics drown in admin. ICBC and WSBC paperwork eat hours every week. New referrals trickle in by phone, email, fax, EMR, and walk-in — and every channel needs a different response. The clinics that thrive are the ones that automate the boring parts so physios can spend their time actually treating people. That's what we install.`,
    services: [
      { name: 'AI Receptionist with ICBC/WSBC intake', desc: 'AI handles incoming calls, captures the right intake information up front (claim number, GP referral status, MVA date), and books appointments. Reduces front-desk load by an average of 15-20 hours a week in a 3-physio clinic.' },
      { name: 'Voice → Report (CL-19 + Form 8)', desc: 'Our flagship for BC physio: dictate a session, get back a fully formatted ICBC CL-19 or WSBC Form 8 with the codes and language ICBC actually accepts. Physiotherapists report saving 4-7 hours per week in reporting alone.' },
      { name: 'Automated reminders + cancellations', desc: 'Same-day cancellations cost a clinic $80-150 a slot. SMS reminder sequences cut cancellation rates by 25-40% in real BC clinics we\'ve installed.' },
      { name: 'New-patient acquisition via local SEO', desc: 'Google Business Profile optimization for the physio categories, ICBC injury-specific local pages, and content that ranks for "physio near me" in your specific city. Most BC physio clinic GBPs are 40-60% complete; we get to 100%.' },
      { name: 'Insurance billing follow-up', desc: 'When a claim is short-paid or denied, the system flags it and queues the appeal. Sounds boring, recovers thousands a month.' },
    ],
    why: [
      `Every physio tool in BC has to handle ICBC and WSBC properly or it\'s useless. We built the BC-specific layer ourselves — see our Easyworks Scribe product, also live for BC clinicians.`,
      `Most physio software was built for the US market and treats Canadian insurance as an afterthought. We didn\'t.`,
      `Every engagement starts with an audit. Most physio builds pair the receptionist with Voice → Report to unlock the reporting time savings, and we run it for you every month.`,
    ],
    faq: [
      { q: 'Will it integrate with Jane?', a: 'Yes. Jane is the dominant EMR in BC physio and we integrate with it natively — appointments flow both ways, charts stay clean.' },
      { q: 'Is the AI compliant for ICBC and WSBC documentation?', a: 'Yes — Voice → Report outputs accept the codes and language ICBC and WSBC require. Every output is reviewed and editable by the physiotherapist before submission; the AI assists, the clinician signs off.' },
      { q: 'Will my older patients be confused by AI calls?', a: 'The AI is configured to sound like a polite human receptionist. We let you adjust the tone, name, and voice. If a patient says they\'d rather talk to a person, the call routes immediately.' },
    ],
  },
  {
    slug: 'ai-for-spas-bc',
    industry: 'Spas + Med-Spas',
    region: 'BC',
    keywords: ['AI for spas BC', 'spa AI receptionist', 'med-spa automation Canada'],
    title: 'AI for Spas and Med-Spas in BC',
    tagline: 'Book at 11pm when your client decides. Upsell during the call. Build a 5-star Google profile.',
    intro: `Spa clients book emotionally and impulsively. They decide at 10pm Wednesday that they want a facial Saturday, and if they can\'t book it in the next 90 seconds, half of them won\'t book at all. Most BC spas don\'t pick up after 7pm. Most don\'t have online booking that actually works on mobile. Most don\'t follow up on a treatment plan. We fix all three.`,
    services: [
      { name: 'AI Receptionist (24/7 booking)', desc: 'Client calls at any hour, the AI books the right service into the right room with the right esthetician. Handles the basics ("how long does it take," "what should I wear," "is parking free") without burning your front desk\'s time during the day.' },
      { name: 'Treatment-plan follow-up', desc: 'A client who comes in for a facial often needs the next one in 4-6 weeks. The system queues the reminder, suggests rebooking, and offers a small loyalty incentive at the right moment. Significant rebooking lift in real spas we run this for.' },
      { name: 'Review velocity engine', desc: 'Every happy client gets a polite Google review request 24 hours after their visit. Spas with proper review automation hit 4.9 stars and dominate the Map Pack — clients with 4.2 stars get skipped over.' },
      { name: 'New-client acquisition via local SEO', desc: 'Google Business Profile optimization with proper categories ("med spa" vs "day spa" vs "skincare clinic" matters more than people think), city-specific content for your service area, and review velocity working together.' },
      { name: 'Upsell during booking', desc: 'When a client books a facial, the AI offers an add-on (LED therapy, lip treatment) at the right price point. Conversion is meaningful when it sounds like a friendly upgrade instead of a sales pitch.' },
    ],
    why: [
      `Spa marketing is brand-led. Most AI tools sound corporate and kill the vibe. Ours is configured for your specific brand voice — we calibrate it during install so it sounds like your front desk would, not a robot.`,
      `BC-specific compliance for med-spas matters. Botox, fillers, and laser treatments have provincial regulations on advertising and intake; we configure the AI to stay on the right side.`,
      `Every engagement starts with an audit. Higher volume spas usually add the content engine for the Instagram and TikTok content that drives the front of funnel, and we run it all for you.`,
    ],
    faq: [
      { q: 'Will it integrate with Mindbody / Vagaro / Boulevard?', a: 'Yes — those three are the most common spa booking systems in BC and we integrate with all of them.' },
      { q: 'How does it handle med-spa regulated services (Botox, filler)?', a: 'It does NOT book regulated services directly. For consultations and follow-ups, yes. For first-time injectables, it always routes to a human consultation. We configure this based on your province and provincial regulator guidance.' },
      { q: 'Can it sound like our brand?', a: 'Yes. We give you a brand-voice form during install — tone, vibe, even the AI\'s name if you want one. The receptionist sounds consistent with your space.' },
    ],
  },
  // ---- Higher ticket verticals (2026-09-04). Source: Sales-Kit/Vertical-Packages/. No pricing anywhere. ----
  {
    slug: 'real-estate',
    industry: 'Real Estate Teams',
    region: 'Canada, the US and worldwide',
    areaServed: ['Canada','United States','United Kingdom'],
    keywords: ['real estate lead follow up system', 'real estate CRM automation', 'ISA alternative'],
    title: 'Growth Systems for Real Estate Teams and Brokerages',
    tagline: 'Leads answered in under a minute. Past clients nurtured for you. Deadlines watched by a system.',
    intro: `Portal leads, ad leads and sign calls go cold in the first five minutes. Agents follow up when they can. Past clients never hear from the team again, and transaction deadlines live on sticky notes. One extra closing pays for the year, so that is where we start: we audit your lead flow, your CRM and your follow up, then build and run the system that turns every lead into a conversation while it is still warm.`,
    services: [
      { name: 'Speed to lead, 24/7', desc: 'Every new lead gets a text and a call within a minute, day or night, from a receptionist that sounds like your team. Sign calls and inbound enquiries are answered, qualified and booked into the right agent’s calendar.' },
      { name: 'Buyer and seller nurture', desc: 'Long nurture sequences for buyers who are six months out and sellers who are “just curious”. Dead leads get reactivated in batches every month instead of dying in the CRM.' },
      { name: 'Deadline and escrow watchdog', desc: 'Contract dates, conditions and closing milestones are tracked by a system that alerts the right person before anything slips. Built first for a Los Angeles team on Lofty, works with Follow Up Boss, kvCORE and Lofty.' },
      { name: 'Reviews, referrals and content', desc: 'Review requests after every closing, referral nudges to past clients, and listing and personal brand content published on a schedule so the team stays top of mind.' },
      { name: 'Managed ads with real attribution', desc: 'Meta and Google campaigns with Fair Housing compliant targeting, budget moved to what closes, and a plain English report showing which source produced the commission.' },
    ],
    why: [
      `Every engagement starts with an audit of your lead sources, response time, CRM hygiene and follow up coverage. You get a written report showing where leads are leaking before we build anything.`,
      `We build only what the audit finds and run it for you every month. Your CRM stays your CRM. Lofty, kvCORE and Follow Up Boss integrate directly.`,
      `Founder led and done for you, not another software subscription your agents ignore. Reference clients in Los Angeles and Houston available by permission.`,
    ],
    faq: [
      { q: 'Does it replace our ISA?', a: 'It handles the first touch, qualification and booking around the clock, which is most of what an ISA does. Your people take over once the lead is talking.' },
      { q: 'Will it work with our CRM?', a: 'Lofty, kvCORE and Follow Up Boss integrate directly. Other CRMs get a structured hand off so nothing is typed twice.' },
      { q: 'Is Fair Housing targeting handled?', a: 'Yes. Ads run under the housing category with compliant targeting, and the creative does the qualifying.' },
    ],
    ctaTitle: 'Ready to see where your leads are dying?',
  },
  {
    slug: 'law',
    industry: 'Law Firms',
    region: 'Canada, the US and the UK',
    areaServed: ['Canada','United States','United Kingdom'],
    keywords: ['law firm intake automation', 'legal answering service alternative', 'law firm marketing'],
    title: 'Growth Systems for Law Firms',
    tagline: 'Every intake call answered and qualified. Consults booked automatically. Confidential by design.',
    intro: `Intake calls come in while you are in court or with a client. A slow callback loses the retainer to the next firm on the search results. Consults no show, reviews stay thin, and intake data gets typed twice. One retained matter pays for the year, so we audit your intake path from first call to signed retainer, then build and run the system that answers, qualifies and books while you practise.`,
    services: [
      { name: 'Intake receptionist, 24/7', desc: 'Calls answered in the firm’s tone, screened by practice area, qualified with your intake questions and booked for a consult. Urgent matters escalate to a person by your rules. The system never gives legal advice.' },
      { name: 'Consult booking and reminders', desc: 'Self booking, confirmations and reminders that cut consult no shows. Intake forms feed your practice management system so nothing is typed twice. Works with Clio and PracticePanther.' },
      { name: 'Reputation and practice area pages', desc: 'Review requests at the right moment in the matter, plus practice area pages and local SEO so the firm shows up for the searches that produce signed clients.' },
      { name: 'High intent search ads', desc: 'Managed search campaigns on the terms people use when they need a lawyer this week, with a report showing cost per signed client instead of cost per click.' },
      { name: 'Dictation to finished documents', desc: 'Voice to Report turns dictation into formatted memos, letters and file notes so the work product is done when the call ends.' },
    ],
    why: [
      `Every engagement starts with an audit of your intake path, after hours coverage, consult flow, reviews and ad spend. You see where retainers are leaking before anything is built.`,
      `Confidentiality and privilege language is built into the scripts. Data residency follows your province, state or bar rules, and the system never discusses the merits of a matter.`,
      `Founder led and done for you. We build only what the audit finds and run it for you every month.`,
    ],
    faq: [
      { q: 'Will it give legal advice?', a: 'No. It answers, qualifies, books and escalates. Anything about the merits of a matter goes to a lawyer.' },
      { q: 'Is client information kept confidential?', a: 'Yes. Confidentiality language is in every script, data residency is set for your jurisdiction, and Canadian firms stay on Canadian hosted infrastructure.' },
      { q: 'Does it work with our practice management software?', a: 'Clio and PracticePanther integrate directly. Other systems get a structured hand off for intake data and appointments.' },
    ],
    ctaTitle: 'Ready to see where your intake is leaking?',
  },
  {
    slug: 'financial',
    industry: 'Mortgage, Insurance and Advisory Firms',
    region: 'Canada, the US and the UK',
    areaServed: ['Canada','United States','United Kingdom'],
    keywords: ['mortgage broker CRM automation', 'insurance agency marketing', 'financial advisor lead follow up'],
    title: 'Growth Systems for Mortgage Brokers, Insurance Agents and Financial Advisors',
    tagline: 'Answer the quote before the next broker does. Documents chased for you. Renewals never missed.',
    intro: `Rate shoppers and quote requests do not wait. Applications stall on missing documents. Renewals and annual reviews slip, and the realtors and accountants who send you business stop hearing from you. Client lifetime value is long and referral driven, so we audit your response path, your document workflow and your renewal calendar, then build and run the system that keeps every file and every partner moving.`,
    services: [
      { name: 'First response in minutes', desc: 'Quote and application requests answered by text and phone within a minute, with compliant scripting that never gives rate or product advice. Pre approval and quote funnels that capture the details you actually need.' },
      { name: 'Document chasing on autopilot', desc: 'Reminder sequences that collect outstanding documents without your assistant sending the same email four times. Files move.' },
      { name: 'Renewal and review automation', desc: 'Renewals, annual reviews and rate holds tracked and reminded automatically, so the book of business stays with you.' },
      { name: 'Referral partner nurture', desc: 'A monthly touch to realtors, accountants and lawyers who send you business, plus reviews that make the referral easy.' },
      { name: 'CRM integration and reporting', desc: 'Works with Finmo, Velocity, Salesforce and Wealthbox. One report shows cost per funded deal or policy, not cost per lead. Voice to Report turns dictation into file notes and client letters.' },
    ],
    why: [
      `Every engagement starts with an audit of your inbound response, application workflow, renewal calendar and partner nurture. You see where deals are stalling before we build anything.`,
      `Compliance first. No rate or product advice from the system, marketing language reviewed against your regulator’s rules, and sign off from your compliance officer before launch.`,
      `Founder led and done for you. We build only what the audit finds and run it every month.`,
    ],
    faq: [
      { q: 'Will the system quote rates or recommend products?', a: 'No. It captures the enquiry, collects details and books the conversation with you. Advice stays with the licensed person.' },
      { q: 'Which CRMs are supported?', a: 'Finmo, Velocity, Salesforce and Wealthbox integrate directly. Others get a structured hand off.' },
      { q: 'How is compliance handled?', a: 'Scripts and marketing copy are written to your regulator’s rules and reviewed by your compliance officer before anything goes live.' },
    ],
    ctaTitle: 'Ready to see where your files are stalling?',
  },
  {
    slug: 'home-services',
    industry: 'Home Service Companies',
    region: 'Canada and the US',
    areaServed: ['Canada','United States'],
    keywords: ['HVAC answering service', 'contractor lead follow up', 'home service marketing'],
    title: 'Growth Systems for HVAC, Roofing, Plumbing, Electrical and Contractors',
    tagline: 'We pick up when you can’t. Quotes chased until they close. More reviews than the company down the road.',
    intro: `The call comes in while you are on the roof or under a sink, and it goes to the next company in the search results. Quotes go out and nobody follows up. Your Google Business Profile is thin next to the big franchises, and you have no idea which ad brought the job. A single missed call can cost thousands, so we audit your phones, your quote follow up and your Google presence, then build and run the system that answers, books and chases while you work.`,
    services: [
      { name: 'Receptionist with dispatch rules', desc: 'Every call answered, the basics quoted, the visit booked and routed by your dispatch rules. Missed calls get a text back in seconds. Works with Jobber, ServiceTitan and Housecall Pro.' },
      { name: 'Quote follow up', desc: 'Every estimate gets a follow up sequence until it is accepted or declined, so the jobs you already quoted stop leaking.' },
      { name: 'Reviews and Google Business Profile', desc: 'Review requests after every completed job, a fully built Google Business Profile and local SEO so you show up in the map pack for your service area.' },
      { name: 'Seasonal campaigns and offers', desc: 'Furnace season, AC season, storm season. Content and offers go out on a calendar, and past customers hear from you before they search.' },
      { name: 'Managed ads and attribution', desc: 'Google Local Services and search ads managed for booked jobs, with a report that shows which ad produced which job. Text to pay on the spot.' },
    ],
    why: [
      `Every engagement starts with an audit of your missed call rate, after hours path, quote follow up, reviews and Google presence. You see where jobs are leaking before we build anything.`,
      `Built around the field software you already use. Jobber, ServiceTitan and Housecall Pro integrate directly.`,
      `Founder led and done for you. We build only what the audit finds and run it every month while you stay on the tools.`,
    ],
    faq: [
      { q: 'Can it quote jobs?', a: 'It quotes the basics you give it, like service call fees and ranges, and books the visit. Detailed quotes stay with you.' },
      { q: 'Does it work with Jobber or ServiceTitan?', a: 'Yes, both, plus Housecall Pro. Bookings and customer records land where your team already works.' },
      { q: 'What about after hours emergencies?', a: 'Emergency calls are routed by your rules, to an on call number or a booked first slot, and never dropped.' },
    ],
    ctaTitle: 'Ready to see how many jobs you are missing?',
  },
  {
    slug: 'dealerships',
    industry: 'Auto Dealerships',
    region: 'Canada and the US',
    areaServed: ['Canada','United States'],
    keywords: ['dealership BDC automation', 'automotive lead follow up', 'dealership marketing'],
    title: 'Growth Systems for Auto Dealerships and Independent Lots',
    tagline: 'A BDC that never sleeps. Internet leads answered in minutes. The service lane on autopilot.',
    intro: `Internet leads get answered hours later. Service customers are never reminded and drift to the quick lube down the street. Inventory content goes stale, reviews lag, and the BDC costs more than it books. We audit your lead response by source, your service reminders and your inventory content, then build and run the system that answers every lead in minutes and keeps the service lane full.`,
    services: [
      { name: 'BDC receptionist and follow up', desc: 'Internet leads, inbound calls and chat answered in minutes, qualified and booked for a test drive or appraisal. Follow up runs until the customer books or says no.' },
      { name: 'Service lane reminders', desc: 'Maintenance reminders, recall notices and rebooking that keep service customers coming back on schedule.' },
      { name: 'Inventory content daily', desc: 'Walkaround reels and inventory posts published every day across Facebook, Instagram and TikTok without anyone on the lot touching a camera app.' },
      { name: 'Reviews and reputation', desc: 'Review requests after every delivery and every service visit, so the lot outranks the franchise store across town.' },
      { name: 'Managed ads and DMS integration', desc: 'Inventory and service offer campaigns tied to sold units and repair orders, reporting through your DMS and CRM.' },
    ],
    why: [
      `Every engagement starts with an audit of lead response time by source, BDC workflow, service reminders, inventory content and reviews. You see where sales are leaking before anything is built.`,
      `Built to work with your DMS and CRM, not replace them. One dashboard from lead to sold.`,
      `Founder led and done for you. We build only what the audit finds and run it every month.`,
    ],
    faq: [
      { q: 'Does it replace our BDC?', a: 'It handles first response, qualification and booking around the clock. Your people close the deal.' },
      { q: 'Will it integrate with our DMS and CRM?', a: 'Yes. Leads, appointments and service bookings land in the systems your team already uses.' },
      { q: 'Who makes the inventory content?', a: 'We do. Walkaround footage or photos from the lot become daily reels and posts on a schedule.' },
    ],
    ctaTitle: 'Ready to see how fast your leads are really answered?',
  },
];
